/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinoLivreRouteImport } from './routes/treino-livre'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreinoRouteImport } from './routes/_authenticated/treino'
import { Route as AuthenticatedRevisaoRouteImport } from './routes/_authenticated/revisao'
import { Route as AuthenticatedPreferenciasRouteImport } from './routes/_authenticated/preferencias'

const TreinoLivreRoute = TreinoLivreRouteImport.update({
  id: '/treino-livre',
  path: '/treino-livre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreinoRoute = AuthenticatedTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisaoRoute = AuthenticatedRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferenciasRoute =
  AuthenticatedPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/treino-livre': typeof TreinoLivreRoute
  '/preferencias': typeof AuthenticatedPreferenciasRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/treino': typeof AuthenticatedTreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/treino-livre': typeof TreinoLivreRoute
  '/preferencias': typeof AuthenticatedPreferenciasRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/treino': typeof AuthenticatedTreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/treino-livre': typeof TreinoLivreRoute
  '/_authenticated/preferencias': typeof AuthenticatedPreferenciasRoute
  '/_authenticated/revisao': typeof AuthenticatedRevisaoRoute
  '/_authenticated/treino': typeof AuthenticatedTreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/treino-livre' | '/preferencias' | '/revisao' | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/treino-livre' | '/preferencias' | '/revisao' | '/treino'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/treino-livre'
    | '/_authenticated/preferencias'
    | '/_authenticated/revisao'
    | '/_authenticated/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TreinoLivreRoute: typeof TreinoLivreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treino-livre': {
      id: '/treino-livre'
      path: '/treino-livre'
      fullPath: '/treino-livre'
      preLoaderRoute: typeof TreinoLivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treino': {
      id: '/_authenticated/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof AuthenticatedTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisao': {
      id: '/_authenticated/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof AuthenticatedRevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferencias': {
      id: '/_authenticated/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof AuthenticatedPreferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPreferenciasRoute: typeof AuthenticatedPreferenciasRoute
  AuthenticatedRevisaoRoute: typeof AuthenticatedRevisaoRoute
  AuthenticatedTreinoRoute: typeof AuthenticatedTreinoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPreferenciasRoute: AuthenticatedPreferenciasRoute,
  AuthenticatedRevisaoRoute: AuthenticatedRevisaoRoute,
  AuthenticatedTreinoRoute: AuthenticatedTreinoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TreinoLivreRoute: TreinoLivreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
